### ISSUE TITLE
Missing Modified Rigid Body Class from Main Taichi Engine

### ISSUE THREAD

**Issue by dodydharma** [haeriamin/mpm#1]
Hi @haeriamin ,
Thanks for publishing the code.
I try to compile your source code,
but it seems that you not only modify the MPM projects, but also the main Taichi Projects (mainly in rigid body class). 
I think it is necessary also to upload the modified class from Taichi, to make the code working for other collaborators.

Here are some missing parts:

`/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp: In function ‘taichi::float32 taichi::extract_float32(const __m128&, int)’:
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp:40:45: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   return reinterpret_cast<float32 *>(&ret)[0];
                                             ^
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp: In lambda function:
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp:477:20: error: ‘struct taichi::RigidBody<3>’ has no member named ‘rigid_force_tmp’
                 r->rigid_force_tmp += force_tmp;
                    ^~~~~~~~~~~~~~~
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp:478:20: error: ‘struct taichi::RigidBody<3>’ has no member named ‘rigid_torque_tmp’
                 r->rigid_torque_tmp += cross(delta_x * grid_pos[node_id] - r->position, force_tmp);
                    ^~~~~~~~~~~~~~~~
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp: In member function ‘void taichi::MPM<dim>::rasterize_optimized(taichi::real) [with int dim = 3; taichi::real = float]’:
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp:668:8: error: ‘struct taichi::RigidBody<3>’ has no member named ‘rigid_force’
     r->rigid_force = r->rigid_force_tmp;
        ^~~~~~~~~~~
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp:668:25: error: ‘struct taichi::RigidBody<3>’ has no member named ‘rigid_force_tmp’
     r->rigid_force = r->rigid_force_tmp;
                         ^~~~~~~~~~~~~~~
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp:669:8: error: ‘struct taichi::RigidBody<3>’ has no member named ‘rigid_torque’; did you mean ‘apply_torque’?
     r->rigid_torque = r->rigid_torque_tmp;
        ^~~~~~~~~~~~
        apply_torque
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp:669:26: error: ‘struct taichi::RigidBody<3>’ has no member named ‘rigid_torque_tmp’
     r->rigid_torque = r->rigid_torque_tmp;
                          ^~~~~~~~~~~~~~~~
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp:670:8: error: ‘struct taichi::RigidBody<3>’ has no member named ‘rigid_force_tmp’
     r->rigid_force_tmp = Vector(0.0_f);
        ^~~~~~~~~~~~~~~
/MPM-NGF-master/taichi/projects/mpm/src/transfer.cpp:671:8: error: ‘struct taichi::RigidBody<3>’ has no member named ‘rigid_torque_tmp’
     r->rigid_torque_tmp = Vector(0.0_f);
        ^~~~~~~~~~~~~~~~
/MPM-NGF-master/taichi/projects/mpm/src/mpm_rigid_body.cpp: In instantiation of ‘void taichi::MPM<dim>::advect_rigid_bodies(taichi::real) [with int dim = 2; taichi::real = float]’:
/MPM-NGF-master/taichi/projects/mpm/src/mpm_rigid_body.cpp:418:50:   required from here
/MPM-NGF-master/taichi/projects/mpm/src/mpm_rigid_body.cpp:304:5: error: no matching function for call to ‘taichi::RigidBody<2>::advance(taichi::real&, taichi::real&, int&)’
     rigid.advance(this->current_t, dt, free_axis_in_position);  // added
     ^~~~~
In file included from /MPM-NGF-master/taichi/projects/mpm/src/articulation.h:8:0,
                 from /MPM-NGF-master/taichi/projects/mpm/src/mpm.h:28,
                 from /MPM-NGF-master/taichi/projects/mpm/src/mpm_rigid_body.cpp:8:
/MPM-NGF-master/taichi/include/taichi/dynamics/rigid_body.h:164:8: note: candidate: void taichi::RigidBody<dim>::advance(taichi::real, taichi::real) [with int dim = 2; taichi::real = float]
   void advance(real t, real dt) {
        ^~~~~~~
/MPM-NGF-master/taichi/include/taichi/dynamics/rigid_body.h:164:8: note:   candidate expects 2 arguments, 3 provided
/MPM-NGF-master/taichi/projects/mpm/src/mpm_rigid_body.cpp: In instantiation of ‘void taichi::MPM<dim>::advect_rigid_bodies(taichi::real) [with int dim = 3; taichi::real = float]’:
/MPM-NGF-master/taichi/projects/mpm/src/mpm_rigid_body.cpp:419:50:   required from here
/MPM-NGF-master/taichi/projects/mpm/src/mpm_rigid_body.cpp:304:5: error: no matching function for call to ‘taichi::RigidBody<3>::advance(taichi::real&, taichi::real&, int&)’
     rigid.advance(this->current_t, dt, free_axis_in_position);  // added
     ^~~~~
In file included from /MPM-NGF-master/taichi/projects/mpm/src/articulation.h:8:0,
                 from /MPM-NGF-master/taichi/projects/mpm/src/mpm.h:28,
                 from /MPM-NGF-master/taichi/projects/mpm/src/mpm_rigid_body.cpp:8:
/MPM-NGF-master/taichi/include/taichi/dynamics/rigid_body.h:164:8: note: candidate: void taichi::RigidBody<dim>::advance(taichi::real, taichi::real) [with int dim = 3; taichi::real = float]
   void advance(real t, real dt) {
        ^~~~~~~
/MPM-NGF-master/taichi/include/taichi/dynamics/rigid_body.h:164:8: note:   candidate expects 2 arguments, 3 provided
/MPM-NGF-master/taichi/projects/mpm/src/visualize.cpp: In instantiation of ‘taichi::MPM<dim>::write_rigid_body(const taichi::RigidBody<dim>*, const string&) const::<lambda(const auto:55&)> [with auto:55 = taichi::STATIC_IF::identity; int dim = 3]’:
/MPM-NGF-master/taichi/include/taichi/common/meta.h:91:6:   required from ‘void taichi::STATIC_IF::statement<false>::else_(const F&) [with F = taichi::MPM<dim>::write_rigid_body(const taichi::RigidBody<dim>*, const string&) const [with int dim = 3; std::__cxx11::string = std::__cxx11::basic_string<char>]::<lambda(const auto:55&)>]’
/MPM-NGF-master/taichi/projects/mpm/src/visualize.cpp:136:3:   required from ‘void taichi::MPM<dim>::write_rigid_body(const taichi::RigidBody<dim>*, const string&) const [with int dim = 3; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/MPM-NGF-master/taichi/projects/mpm/src/visualize.cpp:251:70:   required from here
/MPM-NGF-master/taichi/projects/mpm/src/visualize.cpp:190:27: error: ‘const struct taichi::RigidBody<3>’ has no member named ‘rigid_force’
     Vector force = rigid->rigid_force;
                    ~~~~~~~^~~~~~~~~~~
/MPM-NGF-master/taichi/projects/mpm/src/visualize.cpp:191:28: error: ‘const struct taichi::RigidBody<3>’ has no member named ‘rigid_torque’; did you mean ‘apply_torque’?
     Vector torque = rigid->rigid_torque;
                     ~~~~~~~^~~~~~~~~~~~
                     apply_torque
projects/mpm/CMakeFiles/taichi_mpm.dir/build.make:224: recipe for target 'projects/mpm/CMakeFiles/taichi_mpm.dir/src/transfer.cpp.o' failed
make[2]: *** [projects/mpm/CMakeFiles/taichi_mpm.dir/src/transfer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
projects/mpm/CMakeFiles/taichi_mpm.dir/build.make:237: recipe for target 'projects/mpm/CMakeFiles/taichi_mpm.dir/src/visualize.cpp.o' failed
make[2]: *** [projects/mpm/CMakeFiles/taichi_mpm.dir/src/visualize.cpp.o] Error 1
In file included from /MPM-NGF-master/taichi/projects/mpm/src/mpm_rigid_body.cpp:8:0:
/MPM-NGF-master/taichi/projects/mpm/src/mpm.h:219:8: error: ‘void taichi::MPM<dim>::parallel_for_each_particle(const T&) [with T = taichi::MPM<dim>::advect_rigid_bodies(taichi::real) [with int dim = 2; taichi::real = float]::<lambda(taichi::MPM<2>::Particle&)>; int dim = 2]’, declared using local type ‘const taichi::MPM<dim>::advect_rigid_bodies(taichi::real) [with int dim = 2; taichi::real = float]::<lambda(taichi::MPM<2>::Particle&)>’, is used but never defined [-fpermissive]
   void parallel_for_each_particle(const T &target) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/MPM-NGF-master/taichi/projects/mpm/src/mpm.h:219:8: error: ‘void taichi::MPM<dim>::parallel_for_each_particle(const T&) [with T = taichi::MPM<dim>::advect_rigid_bodies(taichi::real) [with int dim = 3; taichi::real = float]::<lambda(taichi::MPM<3>::Particle&)>; int dim = 3]’, declared using local type ‘const taichi::MPM<dim>::advect_rigid_bodies(taichi::real) [with int dim = 3; taichi::real = float]::<lambda(taichi::MPM<3>::Particle&)>’, is used but never defined [-fpermissive]
projects/mpm/CMakeFiles/taichi_mpm.dir/build.make:172: recipe for target 'projects/mpm/CMakeFiles/taichi_mpm.dir/src/mpm_rigid_body.cpp.o' failed
make[2]: *** [projects/mpm/CMakeFiles/taichi_mpm.dir/src/mpm_rigid_body.cpp.o] Error 1
CMakeFiles/Makefile2:182: recipe for target 'projects/mpm/CMakeFiles/taichi_mpm.dir/all' failed
make[1]: *** [projects/mpm/CMakeFiles/taichi_mpm.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
  Error: Build failed.
`

**Comment by haeriamin** [comment]
Hi @dodydharma! Thanks for your interest.

I'll try to create a docker container possibly once I get a chance. But in your case, since it seems you're familiar with Taichi, I'll add a folder (named 'modifications') containing the modified files to the repo.

**Comment by dodydharma** [comment]
Thanks @haeriamin .
