### ISSUE TITLE
Build failed and installation failed

### ISSUE THREAD

**Issue by Shatom** [haeriamin/mpm#4]
It is very appreciated for your opening the code. I am going to work with the code.

I run the install.sh script, but got the following error message.

> make[2]: *** [CMakeFiles/taichi_core.dir/build.make:141: CMakeFiles/taichi_core.dir/include/taichi/dynamics/rigid_body.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/taichi_core.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2
>   Error: Build failed.
>   Error: installation failed.

I think maybe there are some problems about the taichi legacy, which was written in the install.sh as follows, 

> wget https://raw.githubusercontent.com/yuanming-hu/taichi/legacy/install.py
> python3 install.py

but not very sure.

How can I solve these errors? Could you give me some idea?

Thanks a lot!

**Comment by Shatom** [comment]
> It is very appreciated for your opening the code. I am going to work with the code.
> 
> I run the install.sh script, but got the following error message.
> 
> > make[2]: *** [CMakeFiles/taichi_core.dir/build.make:141: CMakeFiles/taichi_core.dir/include/taichi/dynamics/rigid_body.cpp.o] Error 1
> > make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/taichi_core.dir/all] Error 2
> > make: *** [Makefile:84: all] Error 2
> > Error: Build failed.
> > Error: installation failed.
> 
> I think maybe there are some problems about the taichi legacy, which was written in the install.sh as follows,
> 
> > wget https://raw.githubusercontent.com/yuanming-hu/taichi/legacy/install.py
> > python3 install.py
> 
> but not very sure.
> 
> How can I solve these errors? Could you give me some idea?
> 
> Thanks a lot!

**Comment by Shatom** [comment]
This error maybe cause of the virtual machine WSL.

**Comment by haeriamin** [comment]
Hi @Shatom, since you have resolved your issue it would be great if you can possibly share your experience, and close the issue.

**Comment by Shatom** [comment]
> This error may be the cause of the virtual machine WSL.

I resolve this issue by changing the WSL version of Ubuntu to 18.04.
