### ISSUE TITLE
How to visualize the result? 

### ISSUE THREAD

**Issue by Shatom** [haeriamin/mpm#5]
I run the code successfully, thanks for your opening the code. It generated some .bgeo files in output/mpm/excav/frames/
I can import those files to the geometry view of Houdini, but can not produce some video or figure shown as the demo. Could you give some tutorial about that? 
Thanks.

**Comment by haeriamin** [comment]
Hi @Shatom, sorry for my late response, and happy to hear you have run the code successfully. Houdini tutorial is another story, I think you should be able to learn that by watching some Youtube videos. However, here I have provided the Houdini file I have created for visualizing the 'excav' case; hope it can help.

https://github.com/haeriamin/MPM-NGF/blob/master/excav.hipnc

**Comment by Shatom** [comment]
@haeriamin Thank you for the information. It is very helpful!
