### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by Retiefasaurus** [haeriamin/mpm#6]
Hi @haeriamin, I like your work and thanks making it publicly available. 

I was trying to compile Taichi MPM with your modifications, but I'm getting the following error in `rigid_body.cpp`:

`error: called
      object type 'int' is not a function or function pointer
      this->inv_inertia = inversed(id(inertia));
`

and in `rigid_body.h`:

`  error: called object
      type 'int' is not a function or function pointer
          inversed(id(inertia).template cast<float64>()).template cast<real>();
`

I was able to install the original Taichi MPM with no problems.

Note: I had to change your install.sh script to get the Taichi legacy branch compiled (https://github.com/yuanming-hu/taichi_mpm/issues/31). Also, I'm currently on Ubuntu 20.04 (I've tried setting up a virtual box with Ubuntu 18 and 16, but I still get some kind of compiler error).

**Comment by haeriamin** [comment]
Hi @Retiefasuarus, thanks for your interest.

Have you tried what suggested in [here](https://github.com/haeriamin/MPM-NGF/issues/4)? It seems to be working on WSL (as opposed to VirtualBox) Ubuntu 18.04 (if you do not want to have a separate Ubuntu on your machine).

No one has really tested it on Ubuntu 20.04 yet.

**Comment by Retiefasaurus** [comment]
Thanks for the reply. I am using Ubuntu as my primary operating system. I will try installing your code on WSL on my home system and provide an update.

**Comment by Retiefasaurus** [comment]
> Hi @Retiefasuarus, thanks for your interest.
> 
> Have you tried what suggested in [here](https://github.com/haeriamin/MPM-NGF/issues/4)? It seems to be working on WSL (as opposed to VirtualBox) Ubuntu 18.04 (if you do not want to have a separate Ubuntu on your machine).
> 
> No one has really tested it on Ubuntu 20.04 yet.

Hi @haeriamin , I successfully install the code on WSL Ubuntu 18. I had some problems with compiling PILLOW and Taichi, but resolved this by adding `python3 -m install --upgrade pip` and `pip3 install -- user Pillow`.

Thanks a lot!
